const { useEffect, useMemo, useState } = React;

const ADMIN_PASSWORD = "Ysterberg@2026";
const STORAGE_KEY = "ysterbergPublicPrimaryCms";
const CMS_SHEET_URL = "https://docs.google.com/spreadsheets/d/13mpsSoVSLcVda8ey0vWtN7zX3JraPNtAe6NBqrBGj3k";

const school = {
  schoolName: "Ysterberg Public Primary School",
  emis: "909132013",
  province: "Limpopo",
  district: "Waterberg District",
  circuit: "Thabazimbi Circuit",
  address: "94 Station Road, Podiphatswa, Regorogile Ext 2, Thabazimbi, Limpopo, 0380",
  email: "ysterbergps96@gmail.com",
  telephone: "014 940 6707",
  cell: "074 736 0480",
  type: "Public Primary School - Quintile 1",
  grades: "Grade R - Grade 7",
  principal: "Mr D.M. Maloleka",
  deputyPrincipal: "Mrs D.M. Motaung",
  departmentalHead: "Mrs G.K. Molebalwa",
  slogan: "Building Knowledge, Discipline and Excellence for Every Learner.",
  whatsapp: "27747360480"
};

const imageCategories = ["Ysterberg primary learners", "South African school assembly", "Limpopo classroom", "Grade 7 natural science", "EMS classroom", "Technology project learners", "NSNP programme", "Sports day school", "School garden", "Teacher helping learners"];
const fallbackImages = [1, 2, 3].map((n) => ({ id: `fallback-${n}`, image: `assets/fallback/school${n}.svg`, thumb: `assets/fallback/school${n}.svg`, author: "Ysterberg placeholder", source: "Local fallback", download: `assets/fallback/school${n}.svg`, link: `assets/fallback/school${n}.svg` }));
const pages = [["home", "Home"], ["about", "About Us"], ["academics", "Academics"], ["subjects", "Subjects"], ["learners", "Learners"], ["parents", "Parents"], ["staff", "Staff Portal"], ["governance", "Governance"], ["gallery", "Gallery"], ["contact", "Contact"], ["privacy", "Privacy"], ["admin", "Admin / CMS"]];
const morePages = [["admissions", "Admissions"], ["announcements", "Announcements"], ["calendar", "Calendar"], ["downloads", "Documents"], ["faq", "FAQ"]];
const categories = ["General Notices", "Parent Meetings", "Assessment Dates", "Term Dates", "Departmental Notices", "Sports and Culture", "Emergency Notices"];
const urgency = ["Normal", "Important", "Urgent"];

const starter = {
  settings: school,
  announcements: [{ id: "n1", title: "Welcome to Ysterberg Public Primary School", date: today(), category: "General Notices", audience: "All", urgency: "Important", message: "Latest notices, events, learner achievements and support programme updates will appear here." }],
  events: [{ id: "e1", title: "School calendar updates", date: today(), time: "07:30", venue: "School office", audience: "All", description: "Upcoming school events will be added by school staff in the Admin / CMS dashboard." }],
  documents: [{ id: "d1", title: "Admission form", category: "Admission Forms", description: "Official admission form.", fileLink: "#", important: true }, { id: "d2", title: "Code of Conduct", category: "School Policies", description: "Learner code of conduct.", fileLink: "#", important: true }, { id: "d3", title: "Assessment plans", category: "Assessment Plans", description: "Assessment and examination planning documents.", fileLink: "#", important: true }],
  faqs: [{ id: "f1", category: "Admissions", question: "How do I apply for admission?", answer: "Visit the school office and request the official admission application form." }],
  admissions: [],
  contacts: []
};

function today() { return new Date().toISOString().slice(0, 10); }
function uid(prefix) { return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function loadData() { try { return { ...starter, ...(JSON.parse(localStorage.getItem(STORAGE_KEY)) || {}) }; } catch { return starter; } }
function saveData(data) { localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); }
function route() { const id = location.hash.replace("#", "") || "home"; return [...pages, ...morePages].some(([p]) => p === id) ? id : "home"; }
function byDate(items) { return [...items].sort((a, b) => String(b.date || "").localeCompare(String(a.date || ""))); }
function upcoming(events) { return [...events].filter((e) => !e.date || e.date >= today()).sort((a, b) => String(a.date).localeCompare(String(b.date))); }
function imageKeys() { const c = window.YSTERBERG_IMAGE_CONFIG || {}; return { unsplash: c.UNSPLASH_KEY || "", pexels: c.PEXELS_KEY || "" }; }

async function searchUnsplash(query, key) {
  if (!key) return [];
  const r = await fetch(`https://api.unsplash.com/search/photos?query=${encodeURIComponent(query)}&per_page=20&orientation=landscape&client_id=${key}`);
  if (!r.ok) throw new Error("Unsplash search failed");
  const d = await r.json();
  return (d.results || []).map((x) => ({ id: `u-${x.id}`, image: x.urls.regular, thumb: x.urls.small, author: x.user.name, source: "Unsplash", download: x.links.download, link: x.links.html }));
}
async function searchPexels(query, key) {
  if (!key) return [];
  const r = await fetch(`https://api.pexels.com/v1/search?query=${encodeURIComponent(query)}&per_page=20`, { headers: { Authorization: key } });
  if (!r.ok) throw new Error("Pexels search failed");
  const d = await r.json();
  return (d.photos || []).map((x) => ({ id: `p-${x.id}`, image: x.src.large, thumb: x.src.medium, author: x.photographer, source: "Pexels", download: x.src.original, link: x.url }));
}
async function getImages(query) {
  try {
    const keys = imageKeys();
    const results = [...await searchUnsplash(query, keys.unsplash), ...await searchPexels(query, keys.pexels)];
    return results.length ? results : fallbackImages.map((x) => ({ ...x, author: "AI-style safe placeholder" }));
  } catch { return fallbackImages.map((x) => ({ ...x, author: "AI-style safe placeholder" })); }
}

function App() {
  const [data, setData] = useState(loadData);
  const [page, setPage] = useState(route);
  const [menu, setMenu] = useState(false);
  useEffect(() => saveData(data), [data]);
  useEffect(() => { const h = () => setPage(route()); addEventListener("hashchange", h); return () => removeEventListener("hashchange", h); }, []);
  const go = (id) => { location.hash = id; setPage(id); setMenu(false); scrollTo({ top: 0, behavior: "smooth" }); };
  const props = { data, setData, go };
  return <><Header page={page} go={go} menu={menu} setMenu={setMenu} /><main>{page === "home" && <Home {...props} />}{page === "about" && <About data={data} />}{page === "academics" && <Academics />}{page === "subjects" && <Subjects />}{page === "learners" && <Learners />}{page === "parents" && <Parents data={data} />}{page === "staff" && <Staff />}{page === "governance" && <Governance />}{page === "gallery" && <Gallery />}{page === "contact" && <Contact data={data} setData={setData} />}{page === "privacy" && <Privacy />}{page === "admin" && <Admin data={data} setData={setData} />}{page === "admissions" && <Admissions data={data} setData={setData} />}{page === "announcements" && <Announcements data={data} />}{page === "calendar" && <Calendar data={data} />}{page === "downloads" && <Downloads data={data} />}{page === "faq" && <FAQ data={data} />}</main><Footer go={go} /><WhatsApp /></>;
}

function Header({ page, go, menu, setMenu }) {
  const nav = (item) => <button key={item[0]} className={page === item[0] ? "active" : ""} onClick={() => go(item[0])}>{item[1]}</button>;
  return <header className="site-header"><button className="brand" onClick={() => go("home")}><span className="brand-mark">YP</span><span><strong>{school.schoolName}</strong><small>EMIS: {school.emis}</small></span></button><button className="menu-toggle" onClick={() => setMenu(!menu)}>Menu</button><nav className={menu ? "main-nav open" : "main-nav"}>{pages.map(nav)}<details><summary>More</summary><div>{morePages.map(nav)}</div></details></nav></header>;
}

function Home({ data, go }) {
  const latest = byDate(data.announcements).slice(0, 3), events = upcoming(data.events).slice(0, 3), docs = data.documents.filter((d) => d.important).slice(0, 3);
  const alert = byDate(data.announcements).find((n) => n.urgency !== "Normal");
  return <><section className="hero"><div className="hero-copy"><p className="eyebrow">{school.type} | {school.district}</p><h1>Welcome to {school.schoolName}</h1><p className="welcome">Serving the learners of Regorogile Ext 2 and the Thabazimbi community through quality education, discipline, inclusive learning, learner support programmes, and academic excellence from Grade R to Grade 7.</p><p className="slogan">{school.slogan}</p><div className="hero-status-grid"><span><strong>EMIS</strong>{school.emis}</span><span><strong>Grades</strong>{school.grades}</span><span><strong>Circuit</strong>{school.circuit}</span></div><div className="hero-actions"><button className="primary-button" onClick={() => go("admissions")}>Admissions</button><button className="secondary-button" onClick={() => go("announcements")}>Latest Notices</button><button className="outline-button" onClick={() => go("gallery")}>Gallery</button></div></div></section>{alert && <section className="notice-strip"><strong>{alert.urgency}:</strong><span>{alert.title} - {alert.message}</span></section>}<section className="section"><Intro eyebrow="Home" title="Latest notices, events and learner support updates." text="The homepage highlights principal messages, notices, events, learner achievements, winter support programmes and approved school documents." /><div className="automation-summary"><article><strong>{latest.length}</strong><span>Latest notices</span></article><article><strong>{events.length}</strong><span>Upcoming events</span></article><article><strong>{docs.length}</strong><span>Important documents</span></article></div><div className="card-grid three"><Card title="Principal Message">Principal: {school.principal}. The school promotes knowledge, discipline and excellence for every learner.</Card><Card title="Winter Support Programmes">Winter classes and learner support updates can be published from the CMS.</Card><Card title="Learner Achievements">Approved learner achievements can be added to the gallery and notices area.</Card></div></section><section className="section"><Intro eyebrow="Latest notices" title="School communication dashboard." /><div className="card-grid three">{latest.map((n) => <Notice key={n.id} n={n} />)}</div></section><section className="section"><Intro eyebrow="Events" title="Upcoming school calendar items." /><div className="card-grid three">{events.map((e) => <Event key={e.id} e={e} />)}</div></section></>;
}

function About() { return <Page eyebrow="About Us" title="Ysterberg Public Primary School profile"><div className="card-grid three"><Card title="School history">Ysterberg Public Primary School serves Podiphatswa, Regorogile Ext 2, Thabazimbi and surrounding communities.</Card><Card title="Vision">To build knowledge, discipline and excellence for every learner.</Card><Card title="Mission">To provide quality CAPS-aligned teaching, learner support, discipline, inclusive learning and academic excellence.</Card><Card title="Values">Knowledge, discipline, excellence, respect, responsibility, care and inclusion.</Card><Card title="EMIS information">EMIS {school.emis}. {school.type}. {school.grades}.</Card><Card title="Leadership">Principal: {school.principal}. Deputy Principal: {school.deputyPrincipal}. Departmental Head: {school.departmentalHead}.</Card></div></Page>; }
function Academics() { return <Page eyebrow="Academics" title="Grade R-7 academic planning"><div className="card-grid three"><ListCard title="Academic documents" items={["Assessment Plans", "Timetables", "ATP Documents", "Examination Information", "Invigilation Policy"]} /><ListCard title="Academic support" items={["Winter Classes", "Reading support", "Numeracy support", "Attendance monitoring"]} /><ListCard title="Quality assurance" items={["Teacher Portfolios", "QMS", "Lesson Observation", "Moderation"]} /></div></Page>; }
function Subjects() { return <Page eyebrow="Subjects" title="CAPS subjects"><div className="card-grid three"><ListCard title="Foundation Phase" items={["Home Language", "English FAL", "Mathematics", "Life Skills"]} /><ListCard title="Intermediate Phase" items={["Mathematics", "Natural Sciences & Technology", "Social Sciences", "Languages", "Life Skills"]} /><ListCard title="Senior Phase" items={["Mathematics", "Natural Sciences", "Technology", "EMS", "Social Sciences", "Creative Arts", "Life Orientation"]} /></div></Page>; }
function Learners() { return <Page eyebrow="Learners" title="Learner support and leadership"><div className="card-grid three"><ListCard title="Learner support" items={["Code of Conduct", "Attendance Monitoring", "Pregnancy Support Policy", "Winter Classes"]} /><ListCard title="Leadership" items={["Prefects", "Learner Leadership", "Responsibility", "Service"]} /><ListCard title="Achievements" items={["Academic improvement", "Positive behaviour", "Regular attendance", "Approved achievements"]} /></div></Page>; }
function Parents({ data }) { return <Page eyebrow="Parents" title="Parent communication and support"><div className="card-grid three"><ListCard title="Parent information" items={["Admissions", "Admission Management", "Attendance Policy", "Parent Communication"]} /><ListCard title="Learning support" items={["Assessment Information", "Homework routines", "Reading at home", "Winter support programmes"]} /><ListCard title="School policy" items={["Religious Policy", "Code of Conduct", "POPIA consent", "Respectful communication"]} /></div><ContactSummary /></Page>; }
function Staff() { return <Page eyebrow="Staff Portal" title="Internal staff resources"><div className="card-grid three"><ListCard title="Teaching files" items={["Teacher Portfolios", "ATP documents", "Assessment plans", "Subject files"]} /><ListCard title="Quality management" items={["QMS", "Lesson Observation", "Quality Assurance", "Moderation tools"]} /><ListCard title="Staff administration" items={["Leave Management", "Staff Movement", "Professional development", "Internal notices"]} /></div></Page>; }
function Governance() { return <Page eyebrow="Governance" title="School governance and accountability"><div className="card-grid three"><ListCard title="Structures" items={["SGB", "FINCOM", "NSNP Committee"]} /><ListCard title="Policies" items={["Policies", "Audit Documents", "Religious Policy", "Attendance Policy"]} /><ListCard title="Accountability" items={["School planning", "Committee records", "Finance oversight", "Community reporting"]} /></div></Page>; }

function Gallery() {
  const [images, setImages] = useState(fallbackImages), [search, setSearch] = useState("South African primary school"), [tab, setTab] = useState("Gallery"), [status, setStatus] = useState("Local fallback images are shown until image API keys are added.");
  async function load(q = search) { setStatus("Loading school-safe image results..."); const next = await getImages(q); setImages(next); setStatus(next.some((x) => x.source !== "Local fallback") ? "Images loaded from approved photo providers. Check consent rules before publishing real learner photos." : "AI/local placeholder mode is active. Add API keys in image-config.js to enable Unsplash and Pexels."); }
  useEffect(() => { load(search); }, []);
  const shown = tab === "AI placeholders" ? fallbackImages.map((x) => ({ ...x, author: "AI-style safe placeholder" })) : images;
  return <section className="gallery-page"><section className="image-hero" style={{ backgroundImage: `linear-gradient(120deg, rgba(8,31,58,.82), rgba(16,47,85,.68)), url('${shown[0]?.image || fallbackImages[0].image}')` }}><div><p className="eyebrow">Ysterberg gallery</p><h1>{school.schoolName}</h1><p>{school.slogan}</p></div></section><div className="section"><Intro eyebrow="Gallery" title="School gallery and approved achievements." text="Only approved photos with written parental consent may be published. Internet images are for safe placeholders and design support only." /><div className="gallery-tabs">{["Gallery", "Hero backgrounds", "Download images", "AI placeholders"].map((x) => <button key={x} className={tab === x ? "active-filter" : ""} onClick={() => setTab(x)}>{x}</button>)}</div><div className="image-search"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search school images" /><button className="primary-button" onClick={() => load(search)}>Search</button></div><div className="category-buttons">{imageCategories.map((c) => <button key={c} onClick={() => { setSearch(c); load(c); }}>{c}</button>)}</div><p className="privacy-mini">{status}</p><div className="photo-grid">{shown.map((img) => <article className="photo-card" key={img.id}><img src={img.image} loading="lazy" alt="School gallery result" /><div><strong>{img.author}</strong><small>{img.source}</small><a href={img.download || img.link || img.image} target="_blank" rel="noreferrer">Download</a></div></article>)}</div></div></section>;
}

function Admissions({ data, setData }) { return <Page eyebrow="Admissions" title="Admissions at Ysterberg Public Primary School"><ListCard ordered title="How to apply" items={["Visit the school office.", "Ask for the official admission application form.", "Complete the form and attach required documents.", "Submit the form to the school office.", "Wait for confirmation from the school."]} /><Enquiry type="admissions" data={data} setData={setData} /></Page>; }
function Contact({ data, setData }) { return <Page eyebrow="Contact" title="Speak to the school office"><div className="two-column"><ContactSummary /><Enquiry type="contacts" data={data} setData={setData} /></div></Page>; }
function Enquiry({ type, data, setData }) { const [form, setForm] = useState({ name: "", phone: "", email: "", message: "", grade: "Grade R", enquiryType: "General", consent: false }), [note, setNote] = useState(""); function submit(e) { e.preventDefault(); if (!form.name || !form.phone || !form.message || !form.consent) return setNote("Please complete required fields and POPIA consent."); const item = { ...form, id: uid(type), status: "New", submittedAt: new Date().toISOString() }; setData({ ...data, [type]: [item, ...data[type]] }); setForm({ name: "", phone: "", email: "", message: "", grade: "Grade R", enquiryType: "General", consent: false }); setNote(`Thank you. ${school.schoolName} has received your enquiry and will contact you.`); } return <form className="contact-form" onSubmit={submit}><h2>{type === "admissions" ? "Admissions enquiry" : "General contact form"}</h2><p className="privacy-mini">{school.schoolName} processes personal information only for school administration, communication, admissions and learner support purposes.</p><label>Name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label><label>Phone<input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} required /></label><label>Email<input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label>{type === "admissions" && <label>Grade<select value={form.grade} onChange={(e) => setForm({ ...form, grade: e.target.value })}>{["Grade R", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7"].map((x) => <option key={x}>{x}</option>)}</select></label>}<label>Message<textarea value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} required /></label><label className="check-row"><input type="checkbox" checked={form.consent} onChange={(e) => setForm({ ...form, consent: e.target.checked })} />I consent to {school.schoolName} processing my personal information for this enquiry.</label><button className="primary-button">Submit enquiry</button>{note && <p className="form-success">{note}</p>}</form>; }
function Announcements({ data }) { return <Page eyebrow="Announcements" title="Latest school notices"><div className="card-grid three">{byDate(data.announcements).map((n) => <Notice key={n.id} n={n} />)}</div></Page>; }
function Calendar({ data }) { return <Page eyebrow="Calendar" title="School events"><div className="card-grid three">{upcoming(data.events).map((e) => <Event key={e.id} e={e} />)}</div></Page>; }
function Downloads({ data }) { return <Page eyebrow="Downloads" title="School documents"><div className="card-grid three">{data.documents.map((d) => <a className="document-card" key={d.id} href={d.fileLink || "#"}><span>{d.category}</span><strong>{d.title}</strong><small>{d.description}</small></a>)}</div></Page>; }
function FAQ({ data }) { return <Page eyebrow="FAQ" title="Frequently asked questions">{data.faqs.map((f) => <details className="faq" key={f.id}><summary>{f.question}</summary><p>{f.answer}</p><small>{f.category}</small></details>)}</Page>; }
function Privacy() { return <Page eyebrow="POPIA Privacy Notice" title="Protecting personal information"><div className="card-grid"><Card title="School administration">The school processes personal information only for administration, communication, admissions and learner support.</Card><Card title="Children's information">Learner photos, names, reports, medical information and private details must be protected.</Card><Card title="Consent">Learner photos and names may only be published with written parental or guardian consent.</Card></div></Page>; }

function Admin({ data, setData }) { const [ok, setOk] = useState(sessionStorage.getItem("ysterbergAdmin") === "yes"), [pw, setPw] = useState(""), [tab, setTab] = useState("Announcements"); if (!ok) return <Page eyebrow="Admin / CMS" title="Admin login"><form className="contact-form" onSubmit={(e) => { e.preventDefault(); if (pw === ADMIN_PASSWORD) { sessionStorage.setItem("ysterbergAdmin", "yes"); setOk(true); } }}><label>Password<input type="password" value={pw} onChange={(e) => setPw(e.target.value)} /></label><button className="primary-button">Login</button><p className="privacy-mini">Temporary demo password: Ysterberg@2026</p></form></Page>; const tabs = ["Announcements", "Events", "Documents", "FAQs", "Admissions", "Contacts", "Settings"]; return <Page eyebrow="Admin / CMS" title="School content management dashboard"><div className="backend-panel"><div><h2>Google Sheets backend</h2><p>CMS spreadsheet: <a href={CMS_SHEET_URL} target="_blank" rel="noreferrer">Ysterberg Public Primary School CMS Data</a></p><p>Use the included Apps Script to connect this dashboard for multiple staff members.</p></div></div><div className="admin-tabs">{tabs.map((t) => <button className={tab === t ? "active-filter" : ""} onClick={() => setTab(t)} key={t}>{t}</button>)}</div>{tab === "Announcements" && <Editor collection="announcements" fields={["title", "date", "category", "audience", "urgency", "message"]} data={data} setData={setData} />}{tab === "Events" && <Editor collection="events" fields={["title", "date", "time", "venue", "audience", "description"]} data={data} setData={setData} />}{tab === "Documents" && <Editor collection="documents" fields={["title", "category", "description", "fileLink"]} data={data} setData={setData} />}{tab === "FAQs" && <Editor collection="faqs" fields={["question", "category", "answer"]} data={data} setData={setData} />}{tab === "Admissions" && <Inbox items={data.admissions} />}{tab === "Contacts" && <Inbox items={data.contacts} />}{tab === "Settings" && <ContactSummary />}</Page>; }
function Editor({ collection, fields, data, setData }) { const empty = Object.fromEntries(fields.map((f) => [f, f === "date" ? today() : f === "category" ? categories[0] : f === "urgency" ? urgency[0] : f === "audience" ? "All" : ""])); const [form, setForm] = useState(empty), [q, setQ] = useState(""); function submit(e) { e.preventDefault(); const item = { ...form, id: uid(collection) }; setData({ ...data, [collection]: [item, ...data[collection]] }); setForm(empty); } const items = data[collection].filter((x) => JSON.stringify(x).toLowerCase().includes(q.toLowerCase())); return <div><form className="manager-form" onSubmit={submit}>{fields.map((f) => <label key={f}>{f}{f === "message" || f === "description" || f === "answer" ? <textarea value={form[f]} onChange={(e) => setForm({ ...form, [f]: e.target.value })} /> : <input value={form[f]} onChange={(e) => setForm({ ...form, [f]: e.target.value })} />}</label>)}<button className="primary-button">Add item</button></form><div className="admin-tools"><label>Search<input value={q} onChange={(e) => setQ(e.target.value)} /></label></div><div className="admin-list">{items.map((item) => <article className="admin-list-item" key={item.id}><div><strong>{item.title || item.question}</strong><p>{item.message || item.description || item.answer}</p></div><button className="danger-button" onClick={() => confirm("Delete this item?") && setData({ ...data, [collection]: data[collection].filter((x) => x.id !== item.id) })}>Delete</button></article>)}</div></div>; }
function Inbox({ items }) { return <div className="admin-list">{items.length ? items.map((x) => <article className="admin-list-item" key={x.id}><strong>{x.name}</strong><small>{x.phone} | {x.email}</small><p>{x.message}</p></article>) : <p>No messages yet.</p>}</div>; }

function Page({ eyebrow, title, children }) { return <section className="section"><Intro eyebrow={eyebrow} title={title} />{children}</section>; }
function Intro({ eyebrow, title, text }) { return <div className="section-intro"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{text && <p>{text}</p>}</div>; }
function Card({ title, children }) { return <article className="page-card"><h3>{title}</h3><p>{children}</p></article>; }
function ListCard({ title, items, ordered }) { const Tag = ordered ? "ol" : "ul"; return <article className="page-card"><h3>{title}</h3><Tag>{items.map((i) => <li key={i}>{i}</li>)}</Tag></article>; }
function Notice({ n }) { return <article className={`notice-card urgency-${String(n.urgency).toLowerCase()}`}><small>{n.date} | {n.category} | {n.audience}</small><h3>{n.title}</h3><p>{n.message}</p><strong>{n.urgency}</strong></article>; }
function Event({ e }) { return <article className="page-card"><h3>{e.title}</h3><p><strong>{e.date} {e.time}</strong></p><p>{e.venue}</p><p>{e.description}</p><small>{e.audience}</small></article>; }
function ContactSummary() { return <div className="summary-card"><h3>{school.schoolName}</h3><dl>{[["EMIS", school.emis], ["Address", school.address], ["Email", school.email], ["Tel/Fax", school.telephone], ["Cell", school.cell], ["District", school.district], ["Circuit", school.circuit], ["Principal", school.principal], ["Deputy Principal", school.deputyPrincipal], ["Departmental Head", school.departmentalHead]].map(([a, b]) => <div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl></div>; }
function Footer({ go }) { return <footer className="site-footer"><div><h2>{school.schoolName}</h2><p>EMIS: {school.emis}</p><p>{school.address}</p><p>Email: {school.email}</p><p>Tel/Fax: {school.telephone} | Cell: {school.cell}</p><p>{school.district} - {school.circuit}</p></div><div><button onClick={() => go("privacy")}>Privacy notice</button><p>Copyright {new Date().getFullYear()} {school.schoolName}. All rights reserved.</p></div></footer>; }
function WhatsApp() { const text = encodeURIComponent("Good day Ysterberg Public Primary School. I would like to enquire about:"); return <a className="whatsapp-button" href={`https://wa.me/${school.whatsapp}?text=${text}`} target="_blank" rel="noreferrer">WhatsApp</a>; }

ReactDOM.createRoot(document.getElementById("root")).render(<App />);
